services:  
  server.game:
    image: gameframex/server.launcher:1.0.0
    container_name: game
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "29100:29100"
      - "29110:29110"
      - "29090:29090"
    networks:
      - frontend
      - backend
    volumes:
      - "./running/hotfix:/app/hotfix"
      - "./running/json:/app/json"
networks:
  frontend:
    # Use a custom driver
    name: gameframex-frontend
    driver: bridge
  backend:
    # Use a custom driver which takes special options
    name: gameframex-backend
    driver: bridge