name: Publish NuGet

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.300
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish GameFrameX.Extension
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: GameFrameX.Extension/GameFrameX.Extension.csproj
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          TAG_COMMIT: true
      - name: Publish GameFrameX.Utility
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: GameFrameX.Utility/GameFrameX.Utility.csproj
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          TAG_COMMIT: true
      - name: Publish GameFrameX.Setting
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: GameFrameX.Setting/GameFrameX.Setting.csproj
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          TAG_COMMIT: true
      - name: Publish GameFrameX.ProtoBuf.Net
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: GameFrameX.ProtoBuf.Net/GameFrameX.ProtoBuf.Net.csproj
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          TAG_COMMIT: true
      - name: Publish GameFrameX.NetWork.HTTP
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: GameFrameX.NetWork.HTTP/GameFrameX.NetWork.HTTP.csproj
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          TAG_COMMIT: true
      - name: Publish GameFrameX.NetWork
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: GameFrameX.NetWork/GameFrameX.NetWork.csproj
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          TAG_COMMIT: true
      - name: Publish GameFrameX.Log
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: GameFrameX.Log/GameFrameX.Log.csproj
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          TAG_COMMIT: true
      - name: Publish GameFrameX.Monitor
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: GameFrameX.Monitor/GameFrameX.Monitor.csproj
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          TAG_COMMIT: true
      - name: Publish GameFrameX.Cache.Memory
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: GameFrameX.Cache.Memory/GameFrameX.Cache.Memory.csproj
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          TAG_COMMIT: true
      - name: Publish GameFrameX.Cache
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: GameFrameX.Cache/GameFrameX.Cache.csproj
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          TAG_COMMIT: true
      - name: Publish GameFrameX.DBServer
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: DataBaseServer/GameFrameX.DBServer/GameFrameX.DBServer.csproj
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          TAG_COMMIT: true
      - name: Publish GameFrameX.DBServer.NoSql
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: DataBaseServer/GameFrameX.DBServer.NoSql/GameFrameX.DBServer.NoSql.csproj
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          TAG_COMMIT: true
      - name: Publish GameFrameX.DBServer.NoSql.Redis
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: DataBaseServer/GameFrameX.DBServer.NoSql.Redis/GameFrameX.DBServer.NoSql.Redis.csproj
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          TAG_COMMIT: true