name: Publish NuGet

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.300

      - name: Install dotnet tool
        run: dotnet tool install -g dotnetCampus.TagToVersion

      - name: Set tag to version
        run: dotnet TagToVersion -t ${{ github.ref }} -f Version.props

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish GameFrameX.Extension
        uses: AlianBlank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: GameFrameX.Extension/GameFrameX.Extension.csproj
          VERSION_FILE_PATH: Version.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.Core
        uses: AlianBlank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: GameFrameX.Core/GameFrameX.Core.csproj
          VERSION_FILE_PATH: Version.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.Core.Abstractions
        uses: AlianBlank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: GameFrameX.Core.Abstractions/GameFrameX.Core.Abstractions.csproj
          VERSION_FILE_PATH: Version.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.Core.Config
        uses: AlianBlank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: GameFrameX.Core.Config/GameFrameX.Core.Config.csproj
          VERSION_FILE_PATH: Version.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.Utility
        uses: AlianBlank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: GameFrameX.Utility/GameFrameX.Utility.csproj
          VERSION_FILE_PATH: Version.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.Setting
        uses: AlianBlank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: GameFrameX.Setting/GameFrameX.Setting.csproj
          VERSION_FILE_PATH: Version.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.StartUp
        uses: AlianBlank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: GameFrameX.StartUp/GameFrameX.StartUp.csproj
          VERSION_FILE_PATH: Version.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.ProtoBuf.Net
        uses: AlianBlank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: GameFrameX.ProtoBuf.Net/GameFrameX.ProtoBuf.Net.csproj
          VERSION_FILE_PATH: Version.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.NetWork
        uses: AlianBlank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: GameFrameX.NetWork/GameFrameX.NetWork.csproj
          VERSION_FILE_PATH: Version.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.NetWork.HTTP
        uses: AlianBlank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: GameFrameX.NetWork.HTTP/GameFrameX.NetWork.HTTP.csproj
          VERSION_FILE_PATH: Version.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.NetWork.Message
        uses: AlianBlank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: GameFrameX.NetWork.Message/GameFrameX.NetWork.Message.csproj
          VERSION_FILE_PATH: Version.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.NetWork.Abstractions
        uses: AlianBlank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: GameFrameX.NetWork.Abstractions/GameFrameX.NetWork.Abstractions.csproj
          VERSION_FILE_PATH: Version.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.NetWork.ChannelBase
        uses: AlianBlank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: GameFrameX.NetWork.ChannelBase/GameFrameX.NetWork.ChannelBase.csproj
          VERSION_FILE_PATH: Version.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.Log
        uses: AlianBlank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: GameFrameX.Log/GameFrameX.Log.csproj
          VERSION_FILE_PATH: Version.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.Monitor
        uses: AlianBlank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: GameFrameX.Monitor/GameFrameX.Monitor.csproj
          VERSION_FILE_PATH: Version.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.DataBase
        uses: AlianBlank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: DataBaseServer/GameFrameX.DataBase/GameFrameX.DataBase.csproj
          VERSION_FILE_PATH: Version.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.DataBase.Mongo
        uses: AlianBlank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: DataBaseServer/GameFrameX.DataBase.Mongo/GameFrameX.DataBase.Mongo.csproj
          VERSION_FILE_PATH: Version.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.DataBase.RDS
        uses: AlianBlank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: DataBaseServer/GameFrameX.DataBase.RDS/GameFrameX.DataBase.RDS.csproj
          VERSION_FILE_PATH: Version.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.DataBase.RDS.MySql
        uses: AlianBlank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: DataBaseServer/GameFrameX.DataBase.RDS.MySql/GameFrameX.DataBase.RDS.MySql.csproj
          VERSION_FILE_PATH: Version.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.DataBase.NoSql
        uses: AlianBlank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: DataBaseServer/GameFrameX.DataBase.NoSql/GameFrameX.DataBase.NoSql.csproj
          VERSION_FILE_PATH: Version.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.DataBase.NoSql.Redis
        uses: AlianBlank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: DataBaseServer/GameFrameX.DataBase.NoSql.Redis/GameFrameX.DataBase.NoSql.Redis.csproj
          VERSION_FILE_PATH: Version.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.ServerManager
        uses: AlianBlank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: GameFrameX.ServerManager/GameFrameX.ServerManager.csproj
          VERSION_FILE_PATH: Version.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.GameAnalytics
        uses: AlianBlank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: GameFrameX.GameAnalytics/GameFrameX.GameAnalytics.csproj
          VERSION_FILE_PATH: Version.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
